//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::MetricKit::*;

#[objc2::interface(
    unsafe super = MXMetric,
    unsafe inherits = [
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "MetricKit_MXMemoryMetric")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type MXMemoryMetric;
}

#[cfg(feature = "MetricKit_MXMemoryMetric")]
unsafe impl NSCoding for MXMemoryMetric {}

#[cfg(feature = "MetricKit_MXMemoryMetric")]
unsafe impl NSObjectProtocol for MXMemoryMetric {}

#[cfg(feature = "MetricKit_MXMemoryMetric")]
unsafe impl NSSecureCoding for MXMemoryMetric {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "MetricKit_MXMemoryMetric")]
    pub type MXMemoryMetric;

    #[cfg(all(
        feature = "Foundation_NSMeasurement",
        feature = "Foundation_NSUnitInformationStorage"
    ))]
    #[objc2::method(sel = "peakMemoryUsage", managed = "Other")]
    pub unsafe fn peakMemoryUsage(&self) -> Id<NSMeasurement<NSUnitInformationStorage>>;

    #[cfg(all(
        feature = "Foundation_NSUnitInformationStorage",
        feature = "MetricKit_MXAverage"
    ))]
    #[objc2::method(sel = "averageSuspendedMemory", managed = "Other")]
    pub unsafe fn averageSuspendedMemory(&self) -> Id<MXAverage<NSUnitInformationStorage>>;
}
