//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreLocation::*;
use crate::Foundation::*;
use crate::HealthKit::*;
use crate::UniformTypeIdentifiers::*;

typed_enum!(
    pub type HKClinicalTypeIdentifier = NSString;
);

extern_static!(HKClinicalTypeIdentifierAllergyRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierConditionRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierImmunizationRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierLabResultRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierMedicationRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierProcedureRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierVitalSignRecord: &'static HKClinicalTypeIdentifier);

extern_static!(HKClinicalTypeIdentifierCoverageRecord: &'static HKClinicalTypeIdentifier);

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "HealthKit_HKObjectType")]
    pub type HKObjectType;

    #[cfg(feature = "HealthKit_HKClinicalType")]
    #[objc2::method(sel = "clinicalTypeForIdentifier:", managed = "Other")]
    pub unsafe fn clinicalTypeForIdentifier(
        identifier: &HKClinicalTypeIdentifier,
    ) -> Option<Id<HKClinicalType>>;
}

#[objc2::interface(
    unsafe super = HKSampleType,
    unsafe inherits = [
        HKObjectType,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "HealthKit_HKClinicalType")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type HKClinicalType;
}

#[cfg(feature = "HealthKit_HKClinicalType")]
unsafe impl NSCoding for HKClinicalType {}

#[cfg(feature = "HealthKit_HKClinicalType")]
unsafe impl NSObjectProtocol for HKClinicalType {}

#[cfg(feature = "HealthKit_HKClinicalType")]
unsafe impl NSSecureCoding for HKClinicalType {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "HealthKit_HKClinicalType")]
    pub type HKClinicalType;
}
