//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreLocation::*;
use crate::EventKit::*;
use crate::Foundation::*;
use crate::MapKit::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "EventKit_EKObject")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type EKObject;
}

#[cfg(feature = "EventKit_EKObject")]
unsafe impl NSObjectProtocol for EKObject {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "EventKit_EKObject")]
    pub type EKObject;

    #[objc2::method(sel = "hasChanges")]
    pub unsafe fn hasChanges(&self) -> bool;

    #[objc2::method(sel = "isNew")]
    pub unsafe fn isNew(&self) -> bool;

    #[objc2::method(sel = "reset")]
    pub unsafe fn reset(&self);

    #[objc2::method(sel = "rollback")]
    pub unsafe fn rollback(&self);

    #[objc2::method(sel = "refresh")]
    pub unsafe fn refresh(&self) -> bool;
}
