//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::ClassKit::*;
use crate::Foundation::*;

#[ns_enum]
#[underlying(NSInteger)]
pub enum CLSProgressReportingCapabilityKind {
    CLSProgressReportingCapabilityKindDuration = 0,
    CLSProgressReportingCapabilityKindPercent = 1,
    CLSProgressReportingCapabilityKindBinary = 2,
    CLSProgressReportingCapabilityKindQuantity = 3,
    CLSProgressReportingCapabilityKindScore = 4,
}

#[objc2::interface(
    unsafe super = CLSObject,
    unsafe inherits = [
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "ClassKit_CLSProgressReportingCapability")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CLSProgressReportingCapability;
}

#[cfg(feature = "ClassKit_CLSProgressReportingCapability")]
unsafe impl NSCoding for CLSProgressReportingCapability {}

#[cfg(feature = "ClassKit_CLSProgressReportingCapability")]
unsafe impl NSObjectProtocol for CLSProgressReportingCapability {}

#[cfg(feature = "ClassKit_CLSProgressReportingCapability")]
unsafe impl NSSecureCoding for CLSProgressReportingCapability {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "ClassKit_CLSProgressReportingCapability")]
    pub type CLSProgressReportingCapability;

    #[objc2::method(sel = "kind")]
    pub unsafe fn kind(&self) -> CLSProgressReportingCapabilityKind;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "details", managed = "Other")]
    pub unsafe fn details(&self) -> Option<Id<NSString>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "initWithKind:details:", managed = "Init")]
    pub unsafe fn initWithKind_details(
        this: Option<Allocated<Self>>,
        kind: CLSProgressReportingCapabilityKind,
        details: Option<&NSString>,
    ) -> Id<Self>;
}
