//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Contacts::*;
use crate::CoreLocation::*;
use crate::Foundation::*;
use crate::MapKit::*;

#[objc2::interface(
    unsafe super = MKShape,
    unsafe inherits = [
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "MapKit_MKMultiPolyline")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type MKMultiPolyline;
}

#[cfg(feature = "MapKit_MKMultiPolyline")]
unsafe impl MKAnnotation for MKMultiPolyline {}

#[cfg(feature = "MapKit_MKMultiPolyline")]
unsafe impl MKOverlay for MKMultiPolyline {}

#[cfg(feature = "MapKit_MKMultiPolyline")]
unsafe impl NSObjectProtocol for MKMultiPolyline {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "MapKit_MKMultiPolyline")]
    pub type MKMultiPolyline;

    #[cfg(all(feature = "Foundation_NSArray", feature = "MapKit_MKPolyline"))]
    #[objc2::method(sel = "initWithPolylines:", managed = "Init")]
    pub unsafe fn initWithPolylines(
        this: Option<Allocated<Self>>,
        polylines: &NSArray<MKPolyline>,
    ) -> Id<Self>;

    #[cfg(all(feature = "Foundation_NSArray", feature = "MapKit_MKPolyline"))]
    #[objc2::method(sel = "polylines", managed = "Other")]
    pub unsafe fn polylines(&self) -> Id<NSArray<MKPolyline>>;
}
