//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSColorSampler")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSColorSampler;
}

#[cfg(feature = "AppKit_NSColorSampler")]
unsafe impl NSObjectProtocol for NSColorSampler {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSColorSampler")]
    pub type NSColorSampler;

    #[cfg(feature = "AppKit_NSColor")]
    #[objc2::method(sel = "showSamplerWithSelectionHandler:")]
    pub unsafe fn showSamplerWithSelectionHandler(
        &self,
        selection_handler: &Block<(*mut NSColor,), ()>,
    );
}
