//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSTouchBarItem,
    unsafe inherits = [
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSGroupTouchBarItem")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSGroupTouchBarItem;
}

#[cfg(feature = "AppKit_NSGroupTouchBarItem")]
unsafe impl NSCoding for NSGroupTouchBarItem {}

#[cfg(feature = "AppKit_NSGroupTouchBarItem")]
unsafe impl NSObjectProtocol for NSGroupTouchBarItem {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSGroupTouchBarItem")]
    pub type NSGroupTouchBarItem;

    #[cfg(feature = "Foundation_NSArray")]
    #[objc2::method(sel = "groupItemWithIdentifier:items:", managed = "Other")]
    pub unsafe fn groupItemWithIdentifier_items(
        identifier: &NSTouchBarItemIdentifier,
        items: &NSArray<NSTouchBarItem>,
    ) -> Id<Self>;

    #[cfg(all(
        feature = "AppKit_NSUserInterfaceCompressionOptions",
        feature = "Foundation_NSArray"
    ))]
    #[objc2::method(
        sel = "groupItemWithIdentifier:items:allowedCompressionOptions:",
        managed = "Other"
    )]
    pub unsafe fn groupItemWithIdentifier_items_allowedCompressionOptions(
        identifier: &NSTouchBarItemIdentifier,
        items: &NSArray<NSTouchBarItem>,
        allowed_compression_options: &NSUserInterfaceCompressionOptions,
    ) -> Id<Self>;

    #[objc2::method(sel = "alertStyleGroupItemWithIdentifier:", managed = "Other")]
    pub unsafe fn alertStyleGroupItemWithIdentifier(
        identifier: &NSTouchBarItemIdentifier,
    ) -> Id<Self>;

    #[cfg(feature = "AppKit_NSTouchBar")]
    #[objc2::method(sel = "groupTouchBar", managed = "Other")]
    pub unsafe fn groupTouchBar(&self) -> Id<NSTouchBar>;

    #[cfg(feature = "AppKit_NSTouchBar")]
    #[objc2::method(sel = "setGroupTouchBar:")]
    pub unsafe fn setGroupTouchBar(&self, group_touch_bar: &NSTouchBar);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "customizationLabel", managed = "Other")]
    pub unsafe fn customizationLabel(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setCustomizationLabel:")]
    pub unsafe fn setCustomizationLabel(&self, customization_label: Option<&NSString>);

    #[objc2::method(sel = "groupUserInterfaceLayoutDirection")]
    pub unsafe fn groupUserInterfaceLayoutDirection(&self) -> NSUserInterfaceLayoutDirection;

    #[objc2::method(sel = "setGroupUserInterfaceLayoutDirection:")]
    pub unsafe fn setGroupUserInterfaceLayoutDirection(
        &self,
        group_user_interface_layout_direction: NSUserInterfaceLayoutDirection,
    );

    #[objc2::method(sel = "prefersEqualWidths")]
    pub unsafe fn prefersEqualWidths(&self) -> bool;

    #[objc2::method(sel = "setPrefersEqualWidths:")]
    pub unsafe fn setPrefersEqualWidths(&self, prefers_equal_widths: bool);

    #[objc2::method(sel = "preferredItemWidth")]
    pub unsafe fn preferredItemWidth(&self) -> CGFloat;

    #[objc2::method(sel = "setPreferredItemWidth:")]
    pub unsafe fn setPreferredItemWidth(&self, preferred_item_width: CGFloat);

    #[cfg(feature = "AppKit_NSUserInterfaceCompressionOptions")]
    #[objc2::method(sel = "effectiveCompressionOptions", managed = "Other")]
    pub unsafe fn effectiveCompressionOptions(&self) -> Id<NSUserInterfaceCompressionOptions>;

    #[cfg(all(
        feature = "AppKit_NSUserInterfaceCompressionOptions",
        feature = "Foundation_NSArray"
    ))]
    #[objc2::method(sel = "prioritizedCompressionOptions", managed = "Other")]
    pub unsafe fn prioritizedCompressionOptions(
        &self,
    ) -> Id<NSArray<NSUserInterfaceCompressionOptions>>;

    #[cfg(all(
        feature = "AppKit_NSUserInterfaceCompressionOptions",
        feature = "Foundation_NSArray"
    ))]
    #[objc2::method(sel = "setPrioritizedCompressionOptions:")]
    pub unsafe fn setPrioritizedCompressionOptions(
        &self,
        prioritized_compression_options: &NSArray<NSUserInterfaceCompressionOptions>,
    );
}

#[objc2::interface(
    unsafe continue,
    impl_attrs = {
        /// Methods declared on superclass `NSTouchBarItem`
    #[cfg(feature = "AppKit_NSGroupTouchBarItem")]
    }
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSGroupTouchBarItem")]
    pub type NSGroupTouchBarItem;

    #[objc2::method(sel = "initWithIdentifier:", managed = "Init")]
    pub unsafe fn initWithIdentifier(
        this: Option<Allocated<Self>>,
        identifier: &NSTouchBarItemIdentifier,
    ) -> Id<Self>;
}
