//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSRuleEditor,
    unsafe inherits = [
        NSControl,
        NSView,
        NSResponder,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSPredicateEditor")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSPredicateEditor;
}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSAccessibility for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSAccessibilityElementProtocol for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSAnimatablePropertyContainer for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSAppearanceCustomization for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSCoding for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSDraggingDestination for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSObjectProtocol for NSPredicateEditor {}

#[cfg(feature = "AppKit_NSPredicateEditor")]
unsafe impl NSUserInterfaceItemIdentification for NSPredicateEditor {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSPredicateEditor")]
    pub type NSPredicateEditor;

    #[cfg(all(
        feature = "AppKit_NSPredicateEditorRowTemplate",
        feature = "Foundation_NSArray"
    ))]
    #[objc2::method(sel = "rowTemplates", managed = "Other")]
    pub unsafe fn rowTemplates(&self) -> Id<NSArray<NSPredicateEditorRowTemplate>>;

    #[cfg(all(
        feature = "AppKit_NSPredicateEditorRowTemplate",
        feature = "Foundation_NSArray"
    ))]
    #[objc2::method(sel = "setRowTemplates:")]
    pub unsafe fn setRowTemplates(&self, row_templates: &NSArray<NSPredicateEditorRowTemplate>);
}

#[objc2::interface(
    unsafe continue,
    impl_attrs = {
        /// Methods declared on superclass `NSControl`
    #[cfg(feature = "AppKit_NSPredicateEditor")]
    }
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSPredicateEditor")]
    pub type NSPredicateEditor;

    #[objc2::method(sel = "initWithFrame:", managed = "Init")]
    pub unsafe fn initWithFrame(this: Option<Allocated<Self>>, frame_rect: NSRect) -> Id<Self>;
}
