//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSControl,
    unsafe inherits = [
        NSView,
        NSResponder,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSStepper")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSStepper;
}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSAccessibility for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSAccessibilityElementProtocol for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSAccessibilityStepper for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSAnimatablePropertyContainer for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSAppearanceCustomization for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSCoding for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSDraggingDestination for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSObjectProtocol for NSStepper {}

#[cfg(feature = "AppKit_NSStepper")]
unsafe impl NSUserInterfaceItemIdentification for NSStepper {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSStepper")]
    pub type NSStepper;

    #[objc2::method(sel = "minValue")]
    pub unsafe fn minValue(&self) -> c_double;

    #[objc2::method(sel = "setMinValue:")]
    pub unsafe fn setMinValue(&self, min_value: c_double);

    #[objc2::method(sel = "maxValue")]
    pub unsafe fn maxValue(&self) -> c_double;

    #[objc2::method(sel = "setMaxValue:")]
    pub unsafe fn setMaxValue(&self, max_value: c_double);

    #[objc2::method(sel = "increment")]
    pub unsafe fn increment(&self) -> c_double;

    #[objc2::method(sel = "setIncrement:")]
    pub unsafe fn setIncrement(&self, increment: c_double);

    #[objc2::method(sel = "valueWraps")]
    pub unsafe fn valueWraps(&self) -> bool;

    #[objc2::method(sel = "setValueWraps:")]
    pub unsafe fn setValueWraps(&self, value_wraps: bool);

    #[objc2::method(sel = "autorepeat")]
    pub unsafe fn autorepeat(&self) -> bool;

    #[objc2::method(sel = "setAutorepeat:")]
    pub unsafe fn setAutorepeat(&self, autorepeat: bool);
}

#[objc2::interface(
    unsafe continue,
    impl_attrs = {
        /// Methods declared on superclass `NSControl`
    #[cfg(feature = "AppKit_NSStepper")]
    }
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSStepper")]
    pub type NSStepper;

    #[objc2::method(sel = "initWithFrame:", managed = "Init")]
    pub unsafe fn initWithFrame(this: Option<Allocated<Self>>, frame_rect: NSRect) -> Id<Self>;
}
