//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::protocol]
pub unsafe trait NSValidatedUserInterfaceItem {
    #[objc2::method(sel = "action")]
    unsafe fn action(&self) -> Option<Sel>;

    #[objc2::method(sel = "tag")]
    unsafe fn tag(&self) -> NSInteger;
}

#[objc2::protocol]
pub unsafe trait NSUserInterfaceValidations {
    #[objc2::method(sel = "validateUserInterfaceItem:")]
    unsafe fn validateUserInterfaceItem(
        &self,
        item: &ProtocolObject<dyn NSValidatedUserInterfaceItem>,
    ) -> bool;
}
