//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::protocol]
pub unsafe trait NSUserActivityRestoring: NSObjectProtocol {
    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "restoreUserActivityState:")]
    unsafe fn restoreUserActivityState(&self, user_activity: &NSUserActivity);
}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSResponder")]
    pub type NSResponder;

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "userActivity", managed = "Other")]
    pub unsafe fn userActivity(&self) -> Option<Id<NSUserActivity>>;

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "setUserActivity:")]
    pub unsafe fn setUserActivity(&self, user_activity: Option<&NSUserActivity>);

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "updateUserActivityState:")]
    pub unsafe fn updateUserActivityState(&self, user_activity: &NSUserActivity);
}

#[cfg(feature = "AppKit_NSResponder")]
unsafe impl NSUserActivityRestoring for NSResponder {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "AppKit_NSDocument")]
    pub type NSDocument;

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "userActivity", managed = "Other")]
    pub unsafe fn userActivity(&self) -> Option<Id<NSUserActivity>>;

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "setUserActivity:")]
    pub unsafe fn setUserActivity(&self, user_activity: Option<&NSUserActivity>);

    #[cfg(feature = "Foundation_NSUserActivity")]
    #[objc2::method(sel = "updateUserActivityState:")]
    pub unsafe fn updateUserActivityState(&self, activity: &NSUserActivity);
}

#[cfg(feature = "AppKit_NSDocument")]
unsafe impl NSUserActivityRestoring for NSDocument {}

extern_static!(NSUserActivityDocumentURLKey: &'static NSString);
