//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

#[objc2::interface(
    unsafe super = DOMNode,
    unsafe inherits = [
        DOMObject,
        WebScriptObject,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[deprecated]
    #[cfg(feature = "WebKit_DOMDocumentFragment")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type DOMDocumentFragment;
}

#[cfg(feature = "WebKit_DOMDocumentFragment")]
unsafe impl DOMEventTarget for DOMDocumentFragment {}

#[cfg(feature = "WebKit_DOMDocumentFragment")]
unsafe impl NSObjectProtocol for DOMDocumentFragment {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "WebKit_DOMDocumentFragment")]
    #[deprecated]
    pub type DOMDocumentFragment;
}
