//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

#[objc2::interface(
    unsafe super = DOMHTMLElement,
    unsafe inherits = [
        DOMElement,
        DOMNode,
        DOMObject,
        WebScriptObject,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[deprecated]
    #[cfg(feature = "WebKit_DOMHTMLAppletElement")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type DOMHTMLAppletElement;
}

#[cfg(feature = "WebKit_DOMHTMLAppletElement")]
unsafe impl DOMEventTarget for DOMHTMLAppletElement {}

#[cfg(feature = "WebKit_DOMHTMLAppletElement")]
unsafe impl NSObjectProtocol for DOMHTMLAppletElement {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "WebKit_DOMHTMLAppletElement")]
    #[deprecated]
    pub type DOMHTMLAppletElement;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "align", managed = "Other")]
    pub unsafe fn align(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAlign:")]
    pub unsafe fn setAlign(&self, align: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "alt", managed = "Other")]
    pub unsafe fn alt(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAlt:")]
    pub unsafe fn setAlt(&self, alt: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "archive", managed = "Other")]
    pub unsafe fn archive(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setArchive:")]
    pub unsafe fn setArchive(&self, archive: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "code", managed = "Other")]
    pub unsafe fn code(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setCode:")]
    pub unsafe fn setCode(&self, code: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "codeBase", managed = "Other")]
    pub unsafe fn codeBase(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setCodeBase:")]
    pub unsafe fn setCodeBase(&self, code_base: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "height", managed = "Other")]
    pub unsafe fn height(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setHeight:")]
    pub unsafe fn setHeight(&self, height: Option<&NSString>);

    #[objc2::method(sel = "hspace")]
    pub unsafe fn hspace(&self) -> c_int;

    #[objc2::method(sel = "setHspace:")]
    pub unsafe fn setHspace(&self, hspace: c_int);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "name", managed = "Other")]
    pub unsafe fn name(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setName:")]
    pub unsafe fn setName(&self, name: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "object", managed = "Other")]
    pub unsafe fn object(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setObject:")]
    pub unsafe fn setObject(&self, object: Option<&NSString>);

    #[objc2::method(sel = "vspace")]
    pub unsafe fn vspace(&self) -> c_int;

    #[objc2::method(sel = "setVspace:")]
    pub unsafe fn setVspace(&self, vspace: c_int);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "width", managed = "Other")]
    pub unsafe fn width(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setWidth:")]
    pub unsafe fn setWidth(&self, width: Option<&NSString>);
}
