//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

#[objc2::interface(
    unsafe super = DOMHTMLElement,
    unsafe inherits = [
        DOMElement,
        DOMNode,
        DOMObject,
        WebScriptObject,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[deprecated]
    #[cfg(feature = "WebKit_DOMHTMLTitleElement")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type DOMHTMLTitleElement;
}

#[cfg(feature = "WebKit_DOMHTMLTitleElement")]
unsafe impl DOMEventTarget for DOMHTMLTitleElement {}

#[cfg(feature = "WebKit_DOMHTMLTitleElement")]
unsafe impl NSObjectProtocol for DOMHTMLTitleElement {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "WebKit_DOMHTMLTitleElement")]
    #[deprecated]
    pub type DOMHTMLTitleElement;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "text", managed = "Other")]
    pub unsafe fn text(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setText:")]
    pub unsafe fn setText(&self, text: Option<&NSString>);
}
