//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

#[objc2::interface(
    unsafe super = DOMObject,
    unsafe inherits = [
        WebScriptObject,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[deprecated]
    #[cfg(feature = "WebKit_DOMXPathExpression")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type DOMXPathExpression;
}

#[cfg(feature = "WebKit_DOMXPathExpression")]
unsafe impl NSObjectProtocol for DOMXPathExpression {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "WebKit_DOMXPathExpression")]
    #[deprecated]
    pub type DOMXPathExpression;

    #[cfg(all(feature = "WebKit_DOMNode", feature = "WebKit_DOMXPathResult"))]
    #[objc2::method(sel = "evaluate:type:inResult:", managed = "Other")]
    pub unsafe fn evaluate_type_inResult(
        &self,
        context_node: Option<&DOMNode>,
        r#type: c_ushort,
        in_result: Option<&DOMXPathResult>,
    ) -> Option<Id<DOMXPathResult>>;
}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "WebKit_DOMXPathExpression")]
    pub type DOMXPathExpression;

    #[cfg(all(feature = "WebKit_DOMNode", feature = "WebKit_DOMXPathResult"))]
    #[deprecated]
    #[objc2::method(sel = "evaluate:::", managed = "Other")]
    pub unsafe fn evaluate(
        &self,
        context_node: Option<&DOMNode>,
        r#type: c_ushort,
        in_result: Option<&DOMXPathResult>,
    ) -> Option<Id<DOMXPathResult>>;
}
