//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::WebKit::*;

#[objc2::protocol]
pub unsafe trait WKURLSchemeHandler: NSObjectProtocol {
    #[cfg(feature = "WebKit_WKWebView")]
    #[objc2::method(sel = "webView:startURLSchemeTask:")]
    unsafe fn webView_startURLSchemeTask(
        &self,
        web_view: &WKWebView,
        url_scheme_task: &ProtocolObject<dyn WKURLSchemeTask>,
    );

    #[cfg(feature = "WebKit_WKWebView")]
    #[objc2::method(sel = "webView:stopURLSchemeTask:")]
    unsafe fn webView_stopURLSchemeTask(
        &self,
        web_view: &WKWebView,
        url_scheme_task: &ProtocolObject<dyn WKURLSchemeTask>,
    );
}
