//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::UniformTypeIdentifiers::*;

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "Foundation_NSString")]
    pub type NSString;

    #[cfg(feature = "UniformTypeIdentifiers_UTType")]
    #[objc2::method(
        sel = "stringByAppendingPathComponent:conformingToType:",
        managed = "Other"
    )]
    pub unsafe fn stringByAppendingPathComponent_conformingToType(
        &self,
        partial_name: &NSString,
        content_type: &UTType,
    ) -> Id<NSString>;

    #[cfg(feature = "UniformTypeIdentifiers_UTType")]
    #[objc2::method(sel = "stringByAppendingPathExtensionForType:", managed = "Other")]
    pub unsafe fn stringByAppendingPathExtensionForType(
        &self,
        content_type: &UTType,
    ) -> Id<NSString>;
}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "Foundation_NSURL")]
    pub type NSURL;

    #[cfg(all(
        feature = "Foundation_NSString",
        feature = "UniformTypeIdentifiers_UTType"
    ))]
    #[objc2::method(
        sel = "URLByAppendingPathComponent:conformingToType:",
        managed = "Other"
    )]
    pub unsafe fn URLByAppendingPathComponent_conformingToType(
        &self,
        partial_name: &NSString,
        content_type: &UTType,
    ) -> Id<NSURL>;

    #[cfg(feature = "UniformTypeIdentifiers_UTType")]
    #[objc2::method(sel = "URLByAppendingPathExtensionForType:", managed = "Other")]
    pub unsafe fn URLByAppendingPathExtensionForType(&self, content_type: &UTType) -> Id<NSURL>;
}
