//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreData::*;
use crate::Foundation::*;

extern_static!(
    NSCoreDataCoreSpotlightDelegateIndexDidUpdateNotification: &'static NSNotificationName
);

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSCoreDataCoreSpotlightDelegate")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSCoreDataCoreSpotlightDelegate;
}

#[cfg(feature = "CoreData_NSCoreDataCoreSpotlightDelegate")]
unsafe impl NSObjectProtocol for NSCoreDataCoreSpotlightDelegate {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSCoreDataCoreSpotlightDelegate")]
    pub type NSCoreDataCoreSpotlightDelegate;

    #[objc2::method(sel = "isIndexingEnabled")]
    pub unsafe fn isIndexingEnabled(&self) -> bool;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "domainIdentifier", managed = "Other")]
    pub unsafe fn domainIdentifier(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "indexName", managed = "Other")]
    pub unsafe fn indexName(&self) -> Option<Id<NSString>>;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[cfg(all(
        feature = "CoreData_NSPersistentStoreCoordinator",
        feature = "CoreData_NSPersistentStoreDescription"
    ))]
    #[objc2::method(sel = "initForStoreWithDescription:coordinator:", managed = "Init")]
    pub unsafe fn initForStoreWithDescription_coordinator(
        this: Option<Allocated<Self>>,
        description: &NSPersistentStoreDescription,
        psc: &NSPersistentStoreCoordinator,
    ) -> Id<Self>;

    #[cfg(all(
        feature = "CoreData_NSManagedObjectModel",
        feature = "CoreData_NSPersistentStoreDescription"
    ))]
    #[deprecated]
    #[objc2::method(sel = "initForStoreWithDescription:model:", managed = "Init")]
    pub unsafe fn initForStoreWithDescription_model(
        this: Option<Allocated<Self>>,
        description: &NSPersistentStoreDescription,
        model: &NSManagedObjectModel,
    ) -> Id<Self>;

    #[objc2::method(sel = "startSpotlightIndexing")]
    pub unsafe fn startSpotlightIndexing(&self);

    #[objc2::method(sel = "stopSpotlightIndexing")]
    pub unsafe fn stopSpotlightIndexing(&self);

    #[cfg(feature = "Foundation_NSError")]
    #[objc2::method(sel = "deleteSpotlightIndexWithCompletionHandler:")]
    pub unsafe fn deleteSpotlightIndexWithCompletionHandler(
        &self,
        completion_handler: &Block<(*mut NSError,), ()>,
    );
}
