//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSPersistentHistoryToken")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSPersistentHistoryToken;
}

#[cfg(feature = "CoreData_NSPersistentHistoryToken")]
unsafe impl NSCoding for NSPersistentHistoryToken {}

#[cfg(feature = "CoreData_NSPersistentHistoryToken")]
unsafe impl NSObjectProtocol for NSPersistentHistoryToken {}

#[cfg(feature = "CoreData_NSPersistentHistoryToken")]
unsafe impl NSSecureCoding for NSPersistentHistoryToken {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSPersistentHistoryToken")]
    pub type NSPersistentHistoryToken;
}
