//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSPropertyMapping")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSPropertyMapping;
}

#[cfg(feature = "CoreData_NSPropertyMapping")]
unsafe impl NSObjectProtocol for NSPropertyMapping {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSPropertyMapping")]
    pub type NSPropertyMapping;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "name", managed = "Other")]
    pub unsafe fn name(&self) -> Option<Id<NSString>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setName:")]
    pub unsafe fn setName(&self, name: Option<&NSString>);

    #[cfg(feature = "Foundation_NSExpression")]
    #[objc2::method(sel = "valueExpression", managed = "Other")]
    pub unsafe fn valueExpression(&self) -> Option<Id<NSExpression>>;

    #[cfg(feature = "Foundation_NSExpression")]
    #[objc2::method(sel = "setValueExpression:")]
    pub unsafe fn setValueExpression(&self, value_expression: Option<&NSExpression>);

    #[cfg(feature = "Foundation_NSDictionary")]
    #[objc2::method(sel = "userInfo", managed = "Other")]
    pub unsafe fn userInfo(&self) -> Option<Id<NSDictionary>>;

    #[cfg(feature = "Foundation_NSDictionary")]
    #[objc2::method(sel = "setUserInfo:")]
    pub unsafe fn setUserInfo(&self, user_info: Option<&NSDictionary>);
}
