//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CoreData::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSQueryGenerationToken")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type NSQueryGenerationToken;
}

#[cfg(feature = "CoreData_NSQueryGenerationToken")]
unsafe impl NSCoding for NSQueryGenerationToken {}

#[cfg(feature = "CoreData_NSQueryGenerationToken")]
unsafe impl NSObjectProtocol for NSQueryGenerationToken {}

#[cfg(feature = "CoreData_NSQueryGenerationToken")]
unsafe impl NSSecureCoding for NSQueryGenerationToken {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CoreData_NSQueryGenerationToken")]
    pub type NSQueryGenerationToken;

    #[objc2::method(sel = "currentQueryGenerationToken", managed = "Other")]
    pub unsafe fn currentQueryGenerationToken() -> Id<NSQueryGenerationToken>;
}
