//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::MailKit::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "MailKit_MEDecodedMessageBanner")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type MEDecodedMessageBanner;
}

#[cfg(feature = "MailKit_MEDecodedMessageBanner")]
unsafe impl NSCoding for MEDecodedMessageBanner {}

#[cfg(feature = "MailKit_MEDecodedMessageBanner")]
unsafe impl NSObjectProtocol for MEDecodedMessageBanner {}

#[cfg(feature = "MailKit_MEDecodedMessageBanner")]
unsafe impl NSSecureCoding for MEDecodedMessageBanner {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "MailKit_MEDecodedMessageBanner")]
    pub type MEDecodedMessageBanner;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "title", managed = "Other")]
    pub unsafe fn title(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "primaryActionTitle", managed = "Other")]
    pub unsafe fn primaryActionTitle(&self) -> Id<NSString>;

    #[objc2::method(sel = "isDismissable")]
    pub unsafe fn isDismissable(&self) -> bool;

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(
        sel = "initWithTitle:primaryActionTitle:dismissable:",
        managed = "Init"
    )]
    pub unsafe fn initWithTitle_primaryActionTitle_dismissable(
        this: Option<Allocated<Self>>,
        title: &NSString,
        primary_action_title: &NSString,
        dismissable: bool,
    ) -> Id<Self>;
}
