//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::SoundAnalysis::*;

#[ns_enum]
#[underlying(NSInteger)]
pub enum SNTimeDurationConstraintType {
    SNTimeDurationConstraintTypeEnumerated = 1,
    SNTimeDurationConstraintTypeRange = 2,
}

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "SoundAnalysis_SNTimeDurationConstraint")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type SNTimeDurationConstraint;
}

#[cfg(feature = "SoundAnalysis_SNTimeDurationConstraint")]
unsafe impl NSObjectProtocol for SNTimeDurationConstraint {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "SoundAnalysis_SNTimeDurationConstraint")]
    pub type SNTimeDurationConstraint;

    #[objc2::method(sel = "type")]
    pub unsafe fn r#type(&self) -> SNTimeDurationConstraintType;

    #[cfg(all(feature = "Foundation_NSArray", feature = "Foundation_NSValue"))]
    #[objc2::method(sel = "enumeratedDurations", managed = "Other")]
    pub unsafe fn enumeratedDurations(&self) -> Id<NSArray<NSValue>>;

    #[cfg(all(feature = "Foundation_NSArray", feature = "Foundation_NSValue"))]
    #[objc2::method(sel = "initWithEnumeratedDurations:", managed = "Init")]
    pub unsafe fn initWithEnumeratedDurations(
        this: Option<Allocated<Self>>,
        enumerated_durations: &NSArray<NSValue>,
    ) -> Id<Self>;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;
}
