//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Contacts::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = CNGroup,
    unsafe inherits = [
        NSObject,
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "Contacts_CNMutableGroup")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CNMutableGroup;
}

#[cfg(feature = "Contacts_CNMutableGroup")]
unsafe impl NSCoding for CNMutableGroup {}

#[cfg(feature = "Contacts_CNMutableGroup")]
unsafe impl NSObjectProtocol for CNMutableGroup {}

#[cfg(feature = "Contacts_CNMutableGroup")]
unsafe impl NSSecureCoding for CNMutableGroup {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "Contacts_CNMutableGroup")]
    pub type CNMutableGroup;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "name", managed = "Other")]
    pub unsafe fn name(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setName:")]
    pub unsafe fn setName(&self, name: &NSString);
}
