//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Contacts::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "Contacts_CNPhoneNumber")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CNPhoneNumber;
}

#[cfg(feature = "Contacts_CNPhoneNumber")]
unsafe impl NSCoding for CNPhoneNumber {}

#[cfg(feature = "Contacts_CNPhoneNumber")]
unsafe impl NSObjectProtocol for CNPhoneNumber {}

#[cfg(feature = "Contacts_CNPhoneNumber")]
unsafe impl NSSecureCoding for CNPhoneNumber {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "Contacts_CNPhoneNumber")]
    pub type CNPhoneNumber;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "phoneNumberWithStringValue:", managed = "Other")]
    pub unsafe fn phoneNumberWithStringValue(string_value: &NSString) -> Option<Id<Self>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "initWithStringValue:", managed = "Init")]
    pub unsafe fn initWithStringValue(
        this: Option<Allocated<Self>>,
        string: &NSString,
    ) -> Option<Id<Self>>;

    #[deprecated = "Use initWithStringValue:"]
    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Option<Id<Self>>;

    #[deprecated = "Use phoneNumberWithStringValue:"]
    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Option<Id<Self>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "stringValue", managed = "Other")]
    pub unsafe fn stringValue(&self) -> Id<NSString>;
}

extern_static!(CNLabelPhoneNumberiPhone: &'static NSString);

extern_static!(CNLabelPhoneNumberAppleWatch: &'static NSString);

extern_static!(CNLabelPhoneNumberMobile: &'static NSString);

extern_static!(CNLabelPhoneNumberMain: &'static NSString);

extern_static!(CNLabelPhoneNumberHomeFax: &'static NSString);

extern_static!(CNLabelPhoneNumberWorkFax: &'static NSString);

extern_static!(CNLabelPhoneNumberOtherFax: &'static NSString);

extern_static!(CNLabelPhoneNumberPager: &'static NSString);
