//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::GameKit::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "GameKit_GKLeaderboardEntry")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type GKLeaderboardEntry;
}

#[cfg(feature = "GameKit_GKLeaderboardEntry")]
unsafe impl NSObjectProtocol for GKLeaderboardEntry {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "GameKit_GKLeaderboardEntry")]
    pub type GKLeaderboardEntry;

    #[cfg(feature = "GameKit_GKPlayer")]
    #[objc2::method(sel = "player", managed = "Other")]
    pub unsafe fn player(&self) -> Id<GKPlayer>;

    #[objc2::method(sel = "rank")]
    pub unsafe fn rank(&self) -> NSInteger;

    #[objc2::method(sel = "score")]
    pub unsafe fn score(&self) -> NSInteger;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "formattedScore", managed = "Other")]
    pub unsafe fn formattedScore(&self) -> Id<NSString>;

    #[objc2::method(sel = "context")]
    pub unsafe fn context(&self) -> NSUInteger;

    #[cfg(feature = "Foundation_NSDate")]
    #[objc2::method(sel = "date", managed = "Other")]
    pub unsafe fn date(&self) -> Id<NSDate>;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;
}
