//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::Foundation::*;
use crate::LocalAuthentication::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "LocalAuthentication_LAPublicKey")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type LAPublicKey;
}

#[cfg(feature = "LocalAuthentication_LAPublicKey")]
unsafe impl NSObjectProtocol for LAPublicKey {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "LocalAuthentication_LAPublicKey")]
    pub type LAPublicKey;

    #[cfg(all(feature = "Foundation_NSData", feature = "Foundation_NSError"))]
    #[objc2::method(sel = "exportBytesWithCompletion:")]
    pub unsafe fn exportBytesWithCompletion(
        &self,
        handler: &Block<(*mut NSData, *mut NSError), ()>,
    );

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;
}
