//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::StoreKit::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "StoreKit_SKAdImpression")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type SKAdImpression;
}

#[cfg(feature = "StoreKit_SKAdImpression")]
unsafe impl NSObjectProtocol for SKAdImpression {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "StoreKit_SKAdImpression")]
    pub type SKAdImpression;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "sourceAppStoreItemIdentifier", managed = "Other")]
    pub unsafe fn sourceAppStoreItemIdentifier(&self) -> Id<NSNumber>;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "setSourceAppStoreItemIdentifier:")]
    pub unsafe fn setSourceAppStoreItemIdentifier(
        &self,
        source_app_store_item_identifier: &NSNumber,
    );

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "advertisedAppStoreItemIdentifier", managed = "Other")]
    pub unsafe fn advertisedAppStoreItemIdentifier(&self) -> Id<NSNumber>;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "setAdvertisedAppStoreItemIdentifier:")]
    pub unsafe fn setAdvertisedAppStoreItemIdentifier(
        &self,
        advertised_app_store_item_identifier: &NSNumber,
    );

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "adNetworkIdentifier", managed = "Other")]
    pub unsafe fn adNetworkIdentifier(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAdNetworkIdentifier:")]
    pub unsafe fn setAdNetworkIdentifier(&self, ad_network_identifier: &NSString);

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "adCampaignIdentifier", managed = "Other")]
    pub unsafe fn adCampaignIdentifier(&self) -> Id<NSNumber>;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "setAdCampaignIdentifier:")]
    pub unsafe fn setAdCampaignIdentifier(&self, ad_campaign_identifier: &NSNumber);

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "sourceIdentifier", managed = "Other")]
    pub unsafe fn sourceIdentifier(&self) -> Id<NSNumber>;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "setSourceIdentifier:")]
    pub unsafe fn setSourceIdentifier(&self, source_identifier: &NSNumber);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "adImpressionIdentifier", managed = "Other")]
    pub unsafe fn adImpressionIdentifier(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAdImpressionIdentifier:")]
    pub unsafe fn setAdImpressionIdentifier(&self, ad_impression_identifier: &NSString);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "adType", managed = "Other")]
    pub unsafe fn adType(&self) -> Option<Id<NSString>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAdType:")]
    pub unsafe fn setAdType(&self, ad_type: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "adDescription", managed = "Other")]
    pub unsafe fn adDescription(&self) -> Option<Id<NSString>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAdDescription:")]
    pub unsafe fn setAdDescription(&self, ad_description: Option<&NSString>);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "adPurchaserName", managed = "Other")]
    pub unsafe fn adPurchaserName(&self) -> Option<Id<NSString>>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setAdPurchaserName:")]
    pub unsafe fn setAdPurchaserName(&self, ad_purchaser_name: Option<&NSString>);

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "timestamp", managed = "Other")]
    pub unsafe fn timestamp(&self) -> Id<NSNumber>;

    #[cfg(feature = "Foundation_NSNumber")]
    #[objc2::method(sel = "setTimestamp:")]
    pub unsafe fn setTimestamp(&self, timestamp: &NSNumber);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "signature", managed = "Other")]
    pub unsafe fn signature(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setSignature:")]
    pub unsafe fn setSignature(&self, signature: &NSString);

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "version", managed = "Other")]
    pub unsafe fn version(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "setVersion:")]
    pub unsafe fn setVersion(&self, version: &NSString);
}
