//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CloudKit::*;
use crate::CoreLocation::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKRecordZoneID")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CKRecordZoneID;
}

#[cfg(feature = "CloudKit_CKRecordZoneID")]
unsafe impl NSCoding for CKRecordZoneID {}

#[cfg(feature = "CloudKit_CKRecordZoneID")]
unsafe impl NSObjectProtocol for CKRecordZoneID {}

#[cfg(feature = "CloudKit_CKRecordZoneID")]
unsafe impl NSSecureCoding for CKRecordZoneID {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKRecordZoneID")]
    pub type CKRecordZoneID;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "initWithZoneName:ownerName:", managed = "Init")]
    pub unsafe fn initWithZoneName_ownerName(
        this: Option<Allocated<Self>>,
        zone_name: &NSString,
        owner_name: &NSString,
    ) -> Id<Self>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "zoneName", managed = "Other")]
    pub unsafe fn zoneName(&self) -> Id<NSString>;

    #[cfg(feature = "Foundation_NSString")]
    #[objc2::method(sel = "ownerName", managed = "Other")]
    pub unsafe fn ownerName(&self) -> Id<NSString>;
}
