//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CloudKit::*;
use crate::CoreLocation::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKSystemSharingUIObserver")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CKSystemSharingUIObserver;
}

#[cfg(feature = "CloudKit_CKSystemSharingUIObserver")]
unsafe impl NSObjectProtocol for CKSystemSharingUIObserver {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKSystemSharingUIObserver")]
    pub type CKSystemSharingUIObserver;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;

    #[cfg(feature = "CloudKit_CKContainer")]
    #[objc2::method(sel = "initWithContainer:", managed = "Init")]
    pub unsafe fn initWithContainer(
        this: Option<Allocated<Self>>,
        container: &CKContainer,
    ) -> Id<Self>;

    #[cfg(all(
        feature = "CloudKit_CKRecordID",
        feature = "CloudKit_CKShare",
        feature = "Foundation_NSError"
    ))]
    #[objc2::method(sel = "systemSharingUIDidSaveShareBlock")]
    pub unsafe fn systemSharingUIDidSaveShareBlock(
        &self,
    ) -> *mut Block<(NonNull<CKRecordID>, *mut CKShare, *mut NSError), ()>;

    #[cfg(all(
        feature = "CloudKit_CKRecordID",
        feature = "CloudKit_CKShare",
        feature = "Foundation_NSError"
    ))]
    #[objc2::method(sel = "setSystemSharingUIDidSaveShareBlock:")]
    pub unsafe fn setSystemSharingUIDidSaveShareBlock(
        &self,
        system_sharing_ui_did_save_share_block: Option<
            &Block<(NonNull<CKRecordID>, *mut CKShare, *mut NSError), ()>,
        >,
    );

    #[cfg(all(feature = "CloudKit_CKRecordID", feature = "Foundation_NSError"))]
    #[objc2::method(sel = "systemSharingUIDidStopSharingBlock")]
    pub unsafe fn systemSharingUIDidStopSharingBlock(
        &self,
    ) -> *mut Block<(NonNull<CKRecordID>, *mut NSError), ()>;

    #[cfg(all(feature = "CloudKit_CKRecordID", feature = "Foundation_NSError"))]
    #[objc2::method(sel = "setSystemSharingUIDidStopSharingBlock:")]
    pub unsafe fn setSystemSharingUIDidStopSharingBlock(
        &self,
        system_sharing_ui_did_stop_sharing_block: Option<
            &Block<(NonNull<CKRecordID>, *mut NSError), ()>,
        >,
    );
}
