//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::CloudKit::*;
use crate::CoreLocation::*;
use crate::Foundation::*;

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKUserIdentity")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type CKUserIdentity;
}

#[cfg(feature = "CloudKit_CKUserIdentity")]
unsafe impl NSCoding for CKUserIdentity {}

#[cfg(feature = "CloudKit_CKUserIdentity")]
unsafe impl NSObjectProtocol for CKUserIdentity {}

#[cfg(feature = "CloudKit_CKUserIdentity")]
unsafe impl NSSecureCoding for CKUserIdentity {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "CloudKit_CKUserIdentity")]
    pub type CKUserIdentity;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;

    #[objc2::method(sel = "new", managed = "New")]
    pub unsafe fn new() -> Id<Self>;

    #[cfg(feature = "CloudKit_CKUserIdentityLookupInfo")]
    #[objc2::method(sel = "lookupInfo", managed = "Other")]
    pub unsafe fn lookupInfo(&self) -> Option<Id<CKUserIdentityLookupInfo>>;

    #[cfg(feature = "Foundation_NSPersonNameComponents")]
    #[objc2::method(sel = "nameComponents", managed = "Other")]
    pub unsafe fn nameComponents(&self) -> Option<Id<NSPersonNameComponents>>;

    #[cfg(feature = "CloudKit_CKRecordID")]
    #[objc2::method(sel = "userRecordID", managed = "Other")]
    pub unsafe fn userRecordID(&self) -> Option<Id<CKRecordID>>;

    #[cfg(all(feature = "Foundation_NSArray", feature = "Foundation_NSString"))]
    #[objc2::method(sel = "contactIdentifiers", managed = "Other")]
    pub unsafe fn contactIdentifiers(&self) -> Id<NSArray<NSString>>;

    #[objc2::method(sel = "hasiCloudAccount")]
    pub unsafe fn hasiCloudAccount(&self) -> bool;
}
