//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AuthenticationServices::*;
use crate::Foundation::*;

#[objc2::protocol]
pub unsafe trait ASPublicKeyCredential: ASAuthorizationCredential {
    #[cfg(feature = "Foundation_NSData")]
    #[objc2::method(sel = "rawClientDataJSON", managed = "Other")]
    unsafe fn rawClientDataJSON(&self) -> Id<NSData>;

    #[cfg(feature = "Foundation_NSData")]
    #[objc2::method(sel = "credentialID", managed = "Other")]
    unsafe fn credentialID(&self) -> Id<NSData>;
}
