//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AuthenticationServices::*;
use crate::Foundation::*;

#[objc2::protocol]
pub unsafe trait ASWebAuthenticationSessionWebBrowserSessionHandling {
    #[cfg(feature = "AuthenticationServices_ASWebAuthenticationSessionRequest")]
    #[objc2::method(sel = "beginHandlingWebAuthenticationSessionRequest:")]
    unsafe fn beginHandlingWebAuthenticationSessionRequest(
        &self,
        request: Option<&ASWebAuthenticationSessionRequest>,
    );

    #[cfg(feature = "AuthenticationServices_ASWebAuthenticationSessionRequest")]
    #[objc2::method(sel = "cancelWebAuthenticationSessionRequest:")]
    unsafe fn cancelWebAuthenticationSessionRequest(
        &self,
        request: Option<&ASWebAuthenticationSessionRequest>,
    );
}
