//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::GameController::*;

#[ns_enum]
#[underlying(NSInteger)]
pub enum GCDeviceBatteryState {
    GCDeviceBatteryStateUnknown = -1,
    GCDeviceBatteryStateDischarging = 0,
    GCDeviceBatteryStateCharging = 1,
    GCDeviceBatteryStateFull = 2,
}

#[objc2::interface(
    unsafe super = NSObject,
    unsafe inherits = [
    ]
)]
extern "Objective-C" {
    #[cfg(feature = "GameController_GCDeviceBattery")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type GCDeviceBattery;
}

#[cfg(feature = "GameController_GCDeviceBattery")]
unsafe impl NSObjectProtocol for GCDeviceBattery {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "GameController_GCDeviceBattery")]
    pub type GCDeviceBattery;

    #[objc2::method(sel = "batteryLevel")]
    pub unsafe fn batteryLevel(&self) -> c_float;

    #[objc2::method(sel = "batteryState")]
    pub unsafe fn batteryState(&self) -> GCDeviceBatteryState;

    #[objc2::method(sel = "init", managed = "Init")]
    pub unsafe fn init(this: Option<Allocated<Self>>) -> Id<Self>;
}
