//! This file has been automatically generated by `objc2`'s `header-translator`.
//! DO NOT EDIT
use crate::common::*;
use crate::AppKit::*;
use crate::Foundation::*;
use crate::GameController::*;

#[objc2::interface(
    unsafe super = GCGamepad,
    unsafe inherits = [
        GCPhysicalInputProfile,
        NSObject,
    ]
)]
extern "Objective-C" {
    #[deprecated = "GCGamepad has been deprecated, use GCExtendedGamepad instead"]
    #[cfg(feature = "GameController_GCGamepadSnapshot")]
    #[derive(Debug, PartialEq, Eq, Hash)]
    pub type GCGamepadSnapshot;
}

#[cfg(feature = "GameController_GCGamepadSnapshot")]
unsafe impl NSObjectProtocol for GCGamepadSnapshot {}

#[objc2::interface(
    unsafe continue,
)]
extern "Objective-C" {
    #[cfg(feature = "GameController_GCGamepadSnapshot")]
    #[deprecated = "GCGamepad has been deprecated, use GCExtendedGamepad instead"]
    pub type GCGamepadSnapshot;

    #[cfg(feature = "Foundation_NSData")]
    #[objc2::method(sel = "snapshotData", managed = "Other")]
    pub unsafe fn snapshotData(&self) -> Id<NSData>;

    #[cfg(feature = "Foundation_NSData")]
    #[objc2::method(sel = "setSnapshotData:")]
    pub unsafe fn setSnapshotData(&self, snapshot_data: &NSData);

    #[cfg(feature = "Foundation_NSData")]
    #[objc2::method(sel = "initWithSnapshotData:", managed = "Init")]
    pub unsafe fn initWithSnapshotData(this: Option<Allocated<Self>>, data: &NSData) -> Id<Self>;

    #[cfg(all(feature = "Foundation_NSData", feature = "GameController_GCController"))]
    #[objc2::method(sel = "initWithController:snapshotData:", managed = "Init")]
    pub unsafe fn initWithController_snapshotData(
        this: Option<Allocated<Self>>,
        controller: &GCController,
        data: &NSData,
    ) -> Id<Self>;
}

extern_struct!(
    #[encoding_name("?")]
    #[deprecated = "GCGamepad has been deprecated, use GCExtendedGamepad instead"]
    pub struct GCGamepadSnapShotDataV100 {
        pub version: u16,
        pub size: u16,
        pub dpadX: c_float,
        pub dpadY: c_float,
        pub buttonA: c_float,
        pub buttonB: c_float,
        pub buttonX: c_float,
        pub buttonY: c_float,
        pub leftShoulder: c_float,
        pub rightShoulder: c_float,
    }
);

extern_fn!(
    #[cfg(feature = "Foundation_NSData")]
    #[deprecated = "GCGamepad has been deprecated, use GCExtendedGamepad instead"]
    pub unsafe fn GCGamepadSnapShotDataV100FromNSData(
        snapshot_data: *mut GCGamepadSnapShotDataV100,
        data: Option<&NSData>,
    ) -> Bool;
);

extern_fn!(
    #[cfg(feature = "Foundation_NSData")]
    #[deprecated = "GCGamepad has been deprecated, use GCExtendedGamepad instead"]
    pub unsafe fn NSDataFromGCGamepadSnapShotDataV100(
        snapshot_data: *mut GCGamepadSnapShotDataV100,
    ) -> *mut NSData;
);
